version: 2

sources:
  - name: coffee_shop
    description: this is the raw data from the postgres database. 
    project: analytics-engineers-club
    #this does not work because data not loaded daily
    # freshness:
    #     error_after:
    #       count: 12
    #       period: hour
    # loaded_at_field: created_at
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: order_items
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: products
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: product_prices
        description: "this table has product prices and the dates the prices were valid"
        columns:
          - name: id
            tests:
              - unique
              - not_null